file(GLOB_RECURSE GLSL_OPTIMIZER_SRC "src/*.c")
file(GLOB_RECURSE GLSL_OPTIMIZER_CPP_SRC "src/*.cpp")

set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -fPIC ")
set(CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -fPIC")

# TODO: add proper endianess detection
add_compile_definitions(-D_LIB -DUTIL_ARCH_LITTLE_ENDIAN=1 -DUTIL_ARCH_BIG_ENDIAN=0 -DUNIX -DHAVE_OPENGL -DHAVE_OPENGL_ES_1 -DHAVE_OPENGL_ES_2 -DHAVE_STRUCT_TIMESPEC -DHAVE_TIMESPEC_GET)

if(ANDROID)
	add_compile_definitions(-DANDROID -DDETECT_OS_ANDROID) 
endif()

add_library(glsl_optimizer ${GLSL_OPTIMIZER_SRC} ${GLSL_OPTIMIZER_CPP_SRC})
