name: Android CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :ltw:assembleRelease
    - name: Upload AAR
      uses: actions/upload-artifact@v4.6.0
      with:
         name: output-aar
         path: ltw/build/outputs/aar/ltw-release.aar
         if-no-files-found: error
       
